version: '3.6'

volumes:
  virtualradar-config:

services:
  # dump1090 ##################################################################
  dump1090:
    image: ${DOCKER_USERNAME}/adsb-dump1090:${TAG:-latest}
    build:
      context: dump1090
      dockerfile: Dockerfile-dump1090
      cache_from:
        - ${DOCKER_USERNAME}/adsb-dump1090
        - ${DOCKER_USERNAME}/adsb-dump1090:${TAG:-latest}
      args:
        DUMP1090_VERSION: v3.6.3
        DUMP1090_TAR_HASH: 5edf3ffce3f1336b27c869d5a031a513f6abb834215c249269fbbcf3356c5caa
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    env_file:
      - variables-dump1090.env
    cap_add:
      - SYS_NICE
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == radio
      restart_policy:
        condition: always
        delay: 5s
      resources:
        reservations:
          cpus: '1.0'

  # flightradar24 #############################################################
  flightradar24:
    image: ${DOCKER_USERNAME}/adsb-flightradar24:${TAG:-latest}
    build:
      context: flightradar24
      dockerfile: Dockerfile-flightradar24
      cache_from:
        - ${DOCKER_USERNAME}/adsb-flightradar24
        - ${DOCKER_USERNAME}/adsb-flightradar24:${TAG:-latest}
      args:
        FR24FEED_VERSION: 1.0.19-15
        FR24FEED_HASH: ea2674b5eaa071d3e469a103971a2d42973014d5fde8fd3b0fe123dbd4f1476b
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-flightradar24.env
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s

  # planefinder ###############################################################
  planefinder:
    image: ${DOCKER_USERNAME}/adsb-planefinder:${TAG:-latest}
    build:
      context: planefinder
      dockerfile: Dockerfile-planefinder
      cache_from:
        - ${DOCKER_USERNAME}/adsb-planefinder
        - ${DOCKER_USERNAME}/adsb-planefinder:${TAG:-latest}
      args:
        PFCLIENT_VERSION: 4.1.1
        PFCLIENT_HASH: c2411ca2c9ce1a6a00c1c8af0ce3f7f9
    ports:
      - "30053:30053/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-planefinder.env
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s

  # adsbexchange ##############################################################
  adsbexchange:
    image: ${DOCKER_USERNAME}/adsb-adsbexchange:${TAG:-latest}
    build:
      context: adsbexchange
      dockerfile: Dockerfile-adsbexchange
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbexchange
        - ${DOCKER_USERNAME}/adsb-adsbexchange:${TAG:-latest}
    depends_on:
      - dump1090
    env_file:
      - variables-adsbexchange.env
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # adsbexchange-mlat #########################################################
  adsbexchange-mlat:
    image: ${DOCKER_USERNAME}/adsb-adsbexchange-mlat:${TAG:-latest}
    build:
      context: adsbexchange-mlat
      dockerfile: Dockerfile-adsbexchange-mlat
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat:${TAG:-latest}
      args:
        MLAT_CLIENT_VERSION: v0.2.10
        MLAT_CLIENT_HASH: 8a570fd502bbba39b37175eff6dbab8372ed1a878266ff96fb33cd65f46eacef
    ports:
      - "30104:30104/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-adsbexchange-mlat.env
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # adsbhub ###################################################################
  adsbhub:
    image: ${DOCKER_USERNAME}/adsb-adsbhub:${TAG:-latest}
    build:
      context: adsbhub
      dockerfile: Dockerfile-adsbhub
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbhub
        - ${DOCKER_USERNAME}/adsb-adsbhub:${TAG:-latest}
    depends_on:
      - dump1090
    env_file:
      - variables-adsbhub.env
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # openskynetwork ############################################################
  openskynetwork:
    image: ${DOCKER_USERNAME}/adsb-openskynetwork:${TAG:-latest}
    build:
      context: openskynetwork
      dockerfile: Dockerfile-openskynetwork
      cache_from:
        - ${DOCKER_USERNAME}/adsb-openskynetwork
        - ${DOCKER_USERNAME}/adsb-openskynetwork:${TAG:-latest}
    ports:
      - "30975:30005/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-openskynetwork.env
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # flightaware ###############################################################
  flightaware:
    image: ${DOCKER_USERNAME}/adsb-flightaware:${TAG:-latest}
    build:
      context: flightaware
      dockerfile: Dockerfile-flightaware
      cache_from:
        - ${DOCKER_USERNAME}/adsb-flightaware
        - ${DOCKER_USERNAME}/adsb-flightaware:${TAG:-latest}
      args:
        PIAWARE_VERSION: 3.6.3
    ports:
      - "30105:30105/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-flightaware.env
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s

  # virtualradar ##############################################################
  virtualradar:
    image: ${DOCKER_USERNAME}/adsb-virtualradar:${TAG:-latest}
    build:
      context: virtualradar
      dockerfile: Dockerfile-virtualradar
      cache_from:
        - ${DOCKER_USERNAME}/adsb-virtualradar
        - ${DOCKER_USERNAME}/adsb-virtualradar:${TAG:-latest}
      args:
        VIRTUALRADAR_HASH: 6a8626cdf82b067318aadb75cee5d4428faed28626e7f49ae77dc9f746abb3fc
        VIRTUALRADAR_WEBADMINPLUGIN_HASH: affa6a92d0454109f5d39d32888a208dee547fb30871719f5ba5ceca2bedf215
    ports:
      - "0.0.0.0:8080:8080/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-virtualradar.env
    volumes:
      - virtualradar-config:/config
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: '0.75'
          memory: 512M

  # modesmixer2 ##############################################################
  modesmixer2:
    image: ${DOCKER_USERNAME}/adsb-modesmixer2:${TAG:-latest}
    build:
      context: modesmixer2
      dockerfile: Dockerfile-modesmixer2
      cache_from:
        - ${DOCKER_USERNAME}/adsb-modesmixer2
        - ${DOCKER_USERNAME}/adsb-modesmixer2:${TAG:-latest}
    ports:
      - "0.0.0.0:8081:8080/tcp"
    depends_on:
      - dump1090
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: '0.75'
          memory: 512M

  # radarbox24 ##############################################################
  radarbox24:
    image: ${DOCKER_USERNAME}/adsb-radarbox24:${TAG:-latest}
    build:
      context: radarbox24
      dockerfile: Dockerfile-radarbox24
      cache_from:
        - ${DOCKER_USERNAME}/adsb-radarbox24
        - ${DOCKER_USERNAME}/adsb-radarbox24:${TAG:-latest}
    depends_on:
      - dump1090
    restart: always
    deploy:
      restart_policy:
        condition: always
        delay: 5s
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
