version: '3.6'

volumes:
  virtualradar-config:

services:
  # dump1090 ##################################################################
  dump1090:
    image: ${DOCKER_USERNAME}/adsb-dump1090:${TAG:-latest}
    build:
      context: dump1090
      dockerfile: Dockerfile-dump1090
      cache_from:
        - ${DOCKER_USERNAME}/adsb-dump1090
        - ${DOCKER_USERNAME}/adsb-dump1090:${TAG:-latest}
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
      - "30105:30105/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  # flightradar24 #############################################################
  flightradar24:
    image: ${DOCKER_USERNAME}/adsb-flightradar24:${TAG:-latest}
    build:
      context: flightradar24
      dockerfile: Dockerfile-flightradar24
      cache_from:
        - ${DOCKER_USERNAME}/adsb-flightradar24
        - ${DOCKER_USERNAME}/adsb-flightradar24:${TAG:-latest}
      args:
        FR24FEED_VERSION: 1.0.25-3
        FR24FEED_HASH: 16ca9d5139eb1bc2dcabcd73611cde049b96392a411f3f4ead3157e676b4bc93
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090
    environment:
      - FR24FEED_KEY=${FR24FEED_KEY}
    restart: unless-stopped 

  # planefinder ###############################################################
  planefinder:
    image: ${DOCKER_USERNAME}/adsb-planefinder:${TAG:-latest}
    build:
      context: planefinder
      dockerfile: Dockerfile-planefinder
      cache_from:
        - ${DOCKER_USERNAME}/adsb-planefinder
        - ${DOCKER_USERNAME}/adsb-planefinder:${TAG:-latest}
      args:
        PFCLIENT_VERSION: 4.1.1
        PFCLIENT_HASH: c2411ca2c9ce1a6a00c1c8af0ce3f7f9
    ports:
      - "30053:30053/tcp"
    depends_on:
      - dump1090
    environment:
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - PLANEFINDER_SHARECODE=${PLANEFINDER_SHARECODE}
    restart: unless-stopped

  # adsbexchange ##############################################################
  adsbexchange:
    image: ${DOCKER_USERNAME}/adsb-adsbexchange:${TAG:-latest}
    build:
      context: adsbexchange
      dockerfile: Dockerfile-adsbexchange
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbexchange
        - ${DOCKER_USERNAME}/adsb-adsbexchange:${TAG:-latest}
    depends_on:
      - dump1090
    restart: unless-stopped

  # adsbexchange-mlat #########################################################
  adsbexchange-mlat:
    image: ${DOCKER_USERNAME}/adsb-adsbexchange-mlat:${TAG:-latest}
    build:
      context: adsbexchange-mlat
      dockerfile: Dockerfile-adsbexchange-mlat
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat:${TAG:-latest}
      args:
        MLAT_CLIENT_VERSION: v0.2.11
        MLAT_CLIENT_HASH: 924f4c97f2664c2a9bbf96e0de514ae4aaa0b1caed81e66b0639e354fdc19c01
    environment:
        - ALTITUDE=$ALTITUDE
        - LATITUDE=$LATITUDE
        - LONGITUDE=$LONGITUDE
        - MLAT_CLIENT_USER=$ADSBEXCHANGE_MLAT_CLIENT_USER 
    ports:
      - "30104:30104/tcp"
    depends_on:
      - dump1090
    restart: unless-stopped

  # adsbhub ###################################################################
  adsbhub:
    image: ${DOCKER_USERNAME}/adsb-adsbhub:${TAG:-latest}
    build:
      context: adsbhub
      dockerfile: Dockerfile-adsbhub
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbhub
        - ${DOCKER_USERNAME}/adsb-adsbhub:${TAG:-latest}
    depends_on:
      - dump1090
    restart: unless-stopped

  # openskynetwork ############################################################
  openskynetwork:
    image: ${DOCKER_USERNAME}/adsb-openskynetwork:${TAG:-latest}
    build:
      context: openskynetwork
      dockerfile: Dockerfile-openskynetwork
      cache_from:
        - ${DOCKER_USERNAME}/adsb-openskynetwork
        - ${DOCKER_USERNAME}/adsb-openskynetwork:${TAG:-latest}
    ports:
      - "30975:30005/tcp"
    depends_on:
      - dump1090
    restart: unless-stopped

  # flightaware ###############################################################
  flightaware:
    image: ${DOCKER_USERNAME}/adsb-flightaware:${TAG:-latest}
    build:
      context: flightaware
      dockerfile: Dockerfile-flightaware
      cache_from:
        - ${DOCKER_USERNAME}/adsb-flightaware
        - ${DOCKER_USERNAME}/adsb-flightaware:${TAG:-latest}
      args:
        PIAWARE_VERSION: 4.0
    environment:
      - FLIGHTAWARE_USERNAME=${FLIGHTAWARE_USERNAME}
      - FLIGHTAWARE_PASSWORD=${FLIGHTAWARE_PASSWORD}
      - FLIGHTAWARE_FEEDER_ID=${FLIGHTAWARE_FEEDER_ID}
      - FLIGHTAWARE_GPS_HOST=${FLIGHTAWARE_GPS_HOST}
    ports:
      - "30106:30106/tcp"
    depends_on:
      - dump1090
    restart: unless-stopped

  # virtualradar ##############################################################
  virtualradar:
    image: ${DOCKER_USERNAME}/adsb-virtualradar:${TAG:-latest}
    build:
      context: virtualradar
      dockerfile: Dockerfile-virtualradar
      cache_from:
        - ${DOCKER_USERNAME}/adsb-virtualradar
        - ${DOCKER_USERNAME}/adsb-virtualradar:${TAG:-latest}
      args:
        VIRTUALRADAR_HASH: b3d956b4e049c97b4fec93452ac5ad14225b3e9b732ed62aeceb1e6cf5b24344
        VIRTUALRADAR_WEBADMINPLUGIN_HASH: affa6a92d0454109f5d39d32888a208dee547fb30871719f5ba5ceca2bedf215
    ports:
      - "0.0.0.0:8080:8080/tcp"
    depends_on:
      - dump1090
    env_file:
      - variables-virtualradar.env
    volumes:
      - virtualradar-config:/config
    restart: unless-stopped

  # modesmixer2 ##############################################################
  modesmixer2:
    image: ${DOCKER_USERNAME}/adsb-modesmixer2:${TAG:-latest}
    build:
      context: modesmixer2
      dockerfile: Dockerfile-modesmixer2
      cache_from:
        - ${DOCKER_USERNAME}/adsb-modesmixer2
        - ${DOCKER_USERNAME}/adsb-modesmixer2:${TAG:-latest}
    environment:
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - GOOGLE_KEY=${GOOGLE_KEY}
    ports:
      - "0.0.0.0:8081:8080/tcp"
    depends_on:
      - dump1090
    restart: unless-stopped

  # radarbox24 ##############################################################
  radarbox24:
    image: ${DOCKER_USERNAME}/adsb-radarbox24:${TAG:-latest}
    build:
      context: radarbox24
      dockerfile: Dockerfile-radarbox24
      cache_from:
        - ${DOCKER_USERNAME}/adsb-radarbox24
        - ${DOCKER_USERNAME}/adsb-radarbox24:${TAG:-latest}
    environment:
      - RADARBOX24_KEY=${RADARBOX24_KEY}
    depends_on:
      - dump1090
    restart: unless-stopped
  # radarbox24-mlat #########################################################
  radarbox24-mlat:
    image: ${DOCKER_USERNAME}/adsb-radarbox24-mlat:${TAG:-latest}
    build:
      context: radarbox24-mlat
      dockerfile: Dockerfile-radarbox24-mlat
      cache_from:
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat
        - ${DOCKER_USERNAME}/adsb-adsbexchange-mlat:${TAG:-latest}
      args:
        MLAT_CLIENT_VERSION: v0.2.11
        MLAT_CLIENT_HASH: 924f4c97f2664c2a9bbf96e0de514ae4aaa0b1caed81e66b0639e354fdc19c01
    environment:
        - MLAT_SERVER=mlat1.rb24.com
        - MLAT_SERVER_PORT=40900
        - ALTITUDE=$ALTITUDE
        - LATITUDE=$LATITUDE
        - LONGITUDE=$LONGITUDE
        - MLAT_CLIENT_USER=${RADARBOX24_MLAT_CLIENT_USER}
    ports:
      - "30114:30104/tcp"
    depends_on:
      - dump1090
    restart: unless-stopped
