FROM multiarch/debian-debootstrap:armhf-stretch-slim as base

ARG PIAWARE_VERSION

ADD http://flightaware.com/adsb/piaware/files/packages/pool/piaware/p/piaware-support/piaware-repository_${PIAWARE_VERSION}_all.deb /

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
RUN dpkg -i /piaware-repository_${PIAWARE_VERSION}_all.deb && \
    DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends piaware && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /piaware-repository_${PIAWARE_VERSION}_all.deb /var/lib/apt/lists/*

COPY piaware.conf /etc/piaware.conf
COPY piaware-runner.sh /usr/bin/piaware-runner

EXPOSE 30106/tcp

ENTRYPOINT ["piaware-runner"]

# Metadata
ARG VCS_REF="Unknown"
LABEL maintainer="jb@nrgup.net" \
      org.label-schema.name="Docker ADS-B - flightaware" \
      org.label-schema.description="Docker container for ADS-B - This is the flightaware.com component" \
      org.label-schema.url="https://github.com/bradsjm/docker-ads-b" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/bradsjm/docker-ads-b" \
      org.label-schema.schema-version="1.0"
