FROM alpine:3.9 as base

RUN apk add --no-cache python3 && \
    rm -rf /usr/share/terminfo

FROM base as builder

RUN apk add --no-cache curl ca-certificates python3-dev gcc libc-dev
RUN pip3 install --no-cache --upgrade pip setuptools wheel && \
    pip3 install --upgrade shiv importlib-resources==0.8

ARG MLAT_CLIENT_VERSION
ARG MLAT_CLIENT_HASH

RUN curl --output mlat-client.tar.gz -L "https://github.com/mutability/mlat-client/archive/${MLAT_CLIENT_VERSION}.tar.gz" && \
    sha256sum mlat-client.tar.gz && echo "${MLAT_CLIENT_HASH}  mlat-client.tar.gz" | sha256sum -c
RUN shiv --python='/usr/bin/env python3' -c mlat-client -o /usr/local/bin/mlat-client /mlat-client.tar.gz

FROM base

COPY --from=builder /usr/local/bin/mlat-client /usr/local/bin/mlat-client
COPY mlat-client-runner.sh /usr/bin/mlat-client-runner

ENV SHIV_ROOT=/tmp
RUN mlat-client -h
EXPOSE 30104/tcp
ENTRYPOINT ["mlat-client-runner"]
