# Base Image ##################################################################
FROM alpine:latest as base

RUN cat /etc/apk/repositories && \
    echo '@edge http://nl.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories && \
    apk add --no-cache tini librtlsdr@edge libusb ncurses-libs


# Builder Image ###############################################################
FROM base as builder

RUN apk add --no-cache \
        curl ca-certificates \
        coreutils make gcc pkgconf \
        ncurses-dev \
        libc-dev librtlsdr-dev@edge libusb-dev


ARG DUMP1090_VERSION=v4.0
ARG DUMP1090_TAR_HASH=49ace5a06da3d51384de83a4199d043c6093ad475909c58317cedece0e9590d1


RUN curl -L --output 'dump1090-fa.tar.gz' "https://github.com/flightaware/dump1090/archive/${DUMP1090_VERSION}.tar.gz" && \
    sha256sum dump1090-fa.tar.gz && echo "${DUMP1090_TAR_HASH}  dump1090-fa.tar.gz" | sha256sum -c
RUN mkdir dump1090 && cd dump1090 && \
    tar -xvf ../dump1090-fa.tar.gz --strip-components=1
WORKDIR dump1090
RUN make BLADERF=no DUMP1090_VERSION="${DUMP1090_VERSION}"
RUN make BLADERF=no test


# Final Image #################################################################
FROM base

COPY --from=builder /dump1090/dump1090 /usr/local/bin/dump1090

# Raw output
EXPOSE 30002/tcp
# Basestation output
EXPOSE 30003/tcp
# Beast output
EXPOSE 30005/tcp

EXPOSE 30105/tcp

ENTRYPOINT ["tini", "--", "nice", "-n", "-5", "dump1090", "--net", "--net-bind-address", "0.0.0.0", "--debug", "n", "--mlat", "--net-heartbeat", "5", "--quiet", "--stats-every", "60", "--lat", "${LATITUDE}", "--lon", "${LONGITUDE}" ]
