FROM multiarch/alpine:armhf-v3.8 as base

RUN apk add --no-cache python3

FROM base as builder

RUN apk add --no-cache git build-base curl ca-certificates python3-dev
RUN pip3 install --upgrade shiv importlib-resources==0.8

ARG MLAT_CLIENT_VERSION
ARG MLAT_CLIENT_HASH

RUN curl --output mlat-client.tar.gz -L "https://github.com/mutability/mlat-client/archive/${MLAT_CLIENT_VERSION}.tar.gz" && \
    sha256sum mlat-client.tar.gz && echo "${MLAT_CLIENT_HASH}  mlat-client.tar.gz" | sha256sum -c
RUN shiv -c mlat-client -o /usr/local/bin/mlat-client /mlat-client.tar.gz

FROM base
COPY --from=builder /usr/local/bin/mlat-client /usr/local/bin/mlat-client
COPY mlat-client-runner.sh /usr/bin/mlat-client-runner

ENV SHIV_ROOT=/tmp
EXPOSE 30104/tcp
ENTRYPOINT ["mlat-client-runner"]
