FROM debian:stretch-slim as base

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends netbase dirmngr gnupg2 ca-certificates apt-transport-https && \
    mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf && \
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 1D043681 && \
    echo 'deb https://apt.rb24.com/ rpi-stable main' > /etc/apt/sources.list.d/rb24.list && \
    apt-get update -y && \
    apt-get install rbfeeder -y && \
    apt-get purge -y dirmngr gnupg2 ca-certificates apt-transport-https && \
    apt-get autoremove -y && \
    rm -rf ~/.gnupg /var/lib/apt/lists/*

EXPOSE 32088

COPY rbfeeder.ini /etc/rbfeeder.ini 
ENTRYPOINT ["/usr/bin/rbfeeder"]
